server:
  host: 0.0.0.0
  port: 8003
model:
  repo_id: ttj/dia-1.6b-safetensors
  config_filename: config.json
  weights_filename: dia-v0_1_bf16.safetensors # dia-v0_1.safetensors
  # Available Whisper model sizes: tiny, base, small, medium, large
  # Language options: use without suffix for multilingual, or add language code
  # suffix like .en (English), .fr (French), .de (German), .es (Spanish), etc.
  # Examples: tiny, tiny.en, base, base.fr, small, medium.de, large
  whisper_model_name: tiny
paths:
  model_cache: ./model_cache
  reference_audio: ./reference_audio
  output: ./outputs
  voices: ./voices
generation_defaults:
  speed_factor: 0.9
  cfg_scale: 3
  temperature: 1.3
  top_p: 0.95
  cfg_filter_top_k: 35
  seed: 42
  split_text: true
  chunk_size: 120
ui_state:
  last_text: Hey, how's it going?
  last_voice_mode: clone
  last_predefined_voice: none
  last_reference_file: FBP_snippet.wav
  last_seed: 42
  last_chunk_size: 120
  last_split_text_enabled: true
  hide_chunk_warning: false
  hide_generation_warning: false
